# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.proto.grpc_model_handler_pb2 as grpc__model__handler__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_model_handler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/models.ModelService/Health',
                request_serializer=grpc__model__handler__pb2.HealthRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.PoolStatus = channel.unary_unary(
                '/models.ModelService/PoolStatus',
                request_serializer=grpc__model__handler__pb2.PoolStatusRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.PoolStatusResponse.FromString,
                _registered_method=True)
        self.GetModelList = channel.unary_unary(
                '/models.ModelService/GetModelList',
                request_serializer=grpc__model__handler__pb2.ModelListRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.ModelListResponse.FromString,
                _registered_method=True)
        self.CreateAndSaveModel = channel.unary_unary(
                '/models.ModelService/CreateAndSaveModel',
                request_serializer=grpc__model__handler__pb2.CreateModelRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.CreateModelResponse.FromString,
                _registered_method=True)
        self.LearnModel = channel.unary_unary(
                '/models.ModelService/LearnModel',
                request_serializer=grpc__model__handler__pb2.LearnModelRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.LearnModelResponse.FromString,
                _registered_method=True)
        self.UpdateModel = channel.unary_unary(
                '/models.ModelService/UpdateModel',
                request_serializer=grpc__model__handler__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.UpdateModelResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/models.ModelService/DeleteModel',
                request_serializer=grpc__model__handler__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.DeleteModelResponse.FromString,
                _registered_method=True)
        self.GetPredictionsFromFile = channel.unary_unary(
                '/models.ModelService/GetPredictionsFromFile',
                request_serializer=grpc__model__handler__pb2.PredictionsRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.PredictionsResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/models.ModelService/GetModel',
                request_serializer=grpc__model__handler__pb2.GetModelRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.GetModelResponse.FromString,
                _registered_method=True)
        self.GetModelHyperparameters = channel.unary_unary(
                '/models.ModelService/GetModelHyperparameters',
                request_serializer=grpc__model__handler__pb2.HyperparametersRequest.SerializeToString,
                response_deserializer=grpc__model__handler__pb2.HyperparametersResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Health и статус
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PoolStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAndSaveModel(self, request, context):
        """Основные операции с моделями
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LearnModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredictionsFromFile(self, request, context):
        """Предсказания и информация
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelHyperparameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=grpc__model__handler__pb2.HealthRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.HealthResponse.SerializeToString,
            ),
            'PoolStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.PoolStatus,
                    request_deserializer=grpc__model__handler__pb2.PoolStatusRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.PoolStatusResponse.SerializeToString,
            ),
            'GetModelList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelList,
                    request_deserializer=grpc__model__handler__pb2.ModelListRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.ModelListResponse.SerializeToString,
            ),
            'CreateAndSaveModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAndSaveModel,
                    request_deserializer=grpc__model__handler__pb2.CreateModelRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.CreateModelResponse.SerializeToString,
            ),
            'LearnModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LearnModel,
                    request_deserializer=grpc__model__handler__pb2.LearnModelRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.LearnModelResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=grpc__model__handler__pb2.UpdateModelRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.UpdateModelResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=grpc__model__handler__pb2.DeleteModelRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.DeleteModelResponse.SerializeToString,
            ),
            'GetPredictionsFromFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictionsFromFile,
                    request_deserializer=grpc__model__handler__pb2.PredictionsRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.PredictionsResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=grpc__model__handler__pb2.GetModelRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.GetModelResponse.SerializeToString,
            ),
            'GetModelHyperparameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelHyperparameters,
                    request_deserializer=grpc__model__handler__pb2.HyperparametersRequest.FromString,
                    response_serializer=grpc__model__handler__pb2.HyperparametersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('models.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/Health',
            grpc__model__handler__pb2.HealthRequest.SerializeToString,
            grpc__model__handler__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PoolStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/PoolStatus',
            grpc__model__handler__pb2.PoolStatusRequest.SerializeToString,
            grpc__model__handler__pb2.PoolStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/GetModelList',
            grpc__model__handler__pb2.ModelListRequest.SerializeToString,
            grpc__model__handler__pb2.ModelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAndSaveModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/CreateAndSaveModel',
            grpc__model__handler__pb2.CreateModelRequest.SerializeToString,
            grpc__model__handler__pb2.CreateModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LearnModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/LearnModel',
            grpc__model__handler__pb2.LearnModelRequest.SerializeToString,
            grpc__model__handler__pb2.LearnModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/UpdateModel',
            grpc__model__handler__pb2.UpdateModelRequest.SerializeToString,
            grpc__model__handler__pb2.UpdateModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/DeleteModel',
            grpc__model__handler__pb2.DeleteModelRequest.SerializeToString,
            grpc__model__handler__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredictionsFromFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/GetPredictionsFromFile',
            grpc__model__handler__pb2.PredictionsRequest.SerializeToString,
            grpc__model__handler__pb2.PredictionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/GetModel',
            grpc__model__handler__pb2.GetModelRequest.SerializeToString,
            grpc__model__handler__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelHyperparameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/models.ModelService/GetModelHyperparameters',
            grpc__model__handler__pb2.HyperparametersRequest.SerializeToString,
            grpc__model__handler__pb2.HyperparametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
